version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Set up JDK
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build project
          command: mvn install -DskipTests=true

  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Set up JDK
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
